--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/CustomKB
build-by-default: true
branches:
- main
projects:
  CustomKB:
    path: ""
    icon: "assets/icon.png"
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
...
